apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orphan-analytics-disk-claim
  namespace: prod-databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: standard-rwo
