apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: prod-workers
  labels:
    cost-center: "finops-workers-909"
    owner: "backend-team"
    pod-security.kubernetes.io/enforce: "baseline"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: queue-worker-service
  namespace: prod-workers
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      labels:
        app: worker
    spec:
      containers:
        - name: worker-app
          image: python:3.9-slim
          command:
            [
              "python3",
              "-c",
              "import time; print('Worker running...'); time.sleep(3600)",
            ]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: queue-worker-hpa
  namespace: prod-workers
  labels:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: queue-worker-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80