apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-backend-api
  namespace: default
  labels:
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: api-server
        image: nginx:alpine
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_PASSWORD
