apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-nvme-ssd-nonexistent
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-postgres-db
  namespace: default
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful-db
  template:
    metadata:
      labels:
        app: stateful-db
    spec:
      containers:
      - name: db
        image: postgres:15-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: example
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: postgres-data-pvc
