apiVersion: v1
kind: Namespace
metadata:
  name: prod-auth
  labels:
    cost-center: "finops-auth-202"
    owner: "security-team"
    pod-security.kubernetes.io/enforce: "baseline"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-service
  namespace: prod-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-auth-service
  template:
    metadata:
      labels:
        app: user-auth-service
    spec:
      containers:
        - name: app
          image: gcr.io/enterprise-platform/user-auth-app:v1.0.0
          env:
            - name: LEGACY_AUTH_VM_ENDPOINT
              value: "http://10.128.0.25:8080/token"
