apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: blocking-catalog-pdb
  namespace: prod-apps
  labels:
    app: config-syncer
spec:
  minAvailable: 100%
  selector:
    matchLabels:
      app: config-syncer